# Generated by Django 3.0.8 on 2020-08-18 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reuniao',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
