# Generated by Django 3.0.8 on 2020-08-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0002_auto_20200817_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='hora_inicio',
            field=models.DateTimeField(),
        ),
    ]
