# Generated by Django 3.0.8 on 2020-08-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0003_auto_20200817_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
